# Generated by Django 3.2.19 on 2023-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podrobnee',
            name='text',
            field=models.TextField(),
        ),
    ]
